### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by cheddar-cheeze** [cheddar-cheeze/anime-rpc#1]
- [ ] discord rich presence 
- [ ] video player
- [ ] dynamic app image changer
- [ ] mal api intergration
- [ ] gui
- [ ] gui installation/ initial setup
- [ ] manga support
